#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Larabros Dockstead', '1.0.0');

$app->add(new Larabros\Dockstead\MakeCommand);

$app->run();
